INSERT INTO job_applied
        (job_id,
        application_sent_data,
        custom_resume,
        resume_file_name,
        cover_letter_sent,
        cover_letter_file_name,
        status)
VALUES  (1,
        '2024-02-01',
        true,
        'resume_01.pdf',
        true,
        'cover_letter_01.pdf',
        'submitted'),
        (
        2,
        '2024-02-05',
        true,
        'resume_02.pdf',
        false,
        'cover_letter_02.pdf',
        'submitted'
        ),
        (3,
        '2024-02-10',
        false,
        'resume_03.pdf',
        true,
        'cover_letter_03.pdf',
        'rejected'),
        (4,
        '2024-02-15',
        true,
        'resume_04.pdf',
        true,
        'cover_letter_04.pdf',
        'submitted'),
        (5,
        '2024-02-20',
        true,
        'resume_05.pdf',
        false,
        'cover_letter_05.pdf',
        'rejected');

        SELECT * FROM job_applied;
